Revert "ANDROID: sched: Export few scheduler symbols for vendor modules"
This partially reverts commit 5695c1ea6568eaf8aa0833a025ee7fbdab1646d4.

A new member 'numa_task_swapped' was added to 'sched_statistics' but is
defined only for CONFIG_NUMA_BALANCING. Since this member is used in
__migrate_swap_task(), the function needs back the #ifdef protection
that was removed for Android kernels.

This fixes the following build issue:

  kernel/sched/core.c:3426:27: error: no member named 'numa_task_swapped' in 'struct sched_statistics'
   3426 |         __schedstat_inc(p->stats.numa_task_swapped);
        |                         ~~~~~~~~ ^

If migrate_swap() is really needed for vendor hooks, this issue needs to
be addressed before it can be exported again.

Fixes: ad6b26b6a0a7 ("sched/numa: add statistics of numa balance task")
Change-Id: Ibea7a82701b75e7554631998b512a6f3021bda8f
Signed-off-by: Carlos Llamas <cmllamas@google.com>